apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mysql
  labels:
    app: mysql
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: mysql
      release: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: {{ .Values.mysql.image }}
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.mysql.rootPassword }}
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.database }}
        ports:
        - containerPort: 3306
          name: mysql
