apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysql.name }}
  labels:
    app: {{ .Values.mysql.labels.app }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.mysql.labels.app }}
  replicas: {{ .Values.mysql.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.labels.app }}
    spec:
      containers:
      - name: {{ .Values.mysql.container.name }}
        image: {{ .Values.mysql.container.image }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.mysql.env.MYSQL_ROOT_PASSWORD }}
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.env.MYSQL_DATABASE }}
        ports:
        - containerPort: {{ .Values.mysql.container.port }}
