apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.name }}
  labels:
    app: {{ .Values.mysql.labels.app }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.mysql.service.port }}
    targetPort: {{ .Values.mysql.service.targetPort }}
  selector:
    app: {{ .Values.mysql.labels.app }}
