apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql-service
  labels:
    app: mysql
    release: {{ .Release.Name }}
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql
    release: {{ .Release.Name }}
