bankapp:
  image:
    repo: 423966983147.dkr.ecr.ap-south-1.amazonaws.com/bankapp-demo
    version: 22
    pullPolicy: IfNotPresent
    gateway: null
  affinity: {}
  nodeSelector: {}
  tolerations: []